type Piantina {
  id: ID!
  cantiereId: ID!
  nome: String!
  livello: Int!
  fileUrl: String!
  larghezza: Int!
  altezza: Int!
  puntiDiScatto: [PuntoDiScatto!]!
  createdAt: String!
  updatedAt: String!
}

type PuntoDiScatto {
  id: ID!
  piantinaId: ID!
  nome: String!
  x: Float!
  y: Float!
  dimensione: String!
  foto360: [Foto360!]!
  createdAt: String!
}

extend type Query {
  piantine(cantiereId: ID!): [Piantina!]!
  piantina(id: ID!): Piantina
  puntoDiScatto(id: ID!): PuntoDiScatto
}

extend type Mutation {
  caricaPiantina(
    cantiereId: ID!
    nome: String!
    livello: Int!
    fileUrl: String!
    larghezza: Int!
    altezza: Int!
  ): Piantina!
  aggiungiPuntoDiScatto(
    piantinaId: ID!
    nome: String!
    x: Float!
    y: Float!
    dimensione: String
  ): PuntoDiScatto!
  aggiornaDimensionePuntoDiScatto(id: ID!, dimensione: String!): PuntoDiScatto!
  spostaPuntoDiScatto(
    id: ID!
    x: Float!
    y: Float!
  ): PuntoDiScatto!
  rinominaPuntoDiScatto(id: ID!, nome: String!): PuntoDiScatto!
  aggiornaDataPuntoDiScatto(id: ID!, data: String!): PuntoDiScatto!
  eliminaPuntoDiScatto(id: ID!): PuntoDiScatto!
  rinominaPiantina(id: ID!, nome: String!): Piantina!
  aggiornaDataPiantina(id: ID!, data: String!): Piantina!
}
